[package]
name = "raytrace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geometric = {path = "../geometric"}
sdl2 = "0.35.2"

[[bin]]
name = "raytracer_demo"
path = "src/demo.rs"

